apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-csh4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-csh4
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-csh4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-csh4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-csh4
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xnvp-tenant/rhtap-demo-app/hacbs-test-project-csh4@sha256:b1c1e80e316b2597de787c571e67b0320cee252f9f4ff0355aea8db7c8cf445b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
