apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-csh4
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xnvp-tenant/rhtap-demo-app/hacbs-test-project-csh4@sha256:c1dc65c4047d7f75d69c77d3cc2494174b7c30a9956b3c588500fe31c2f4a671
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
